# Generated by Django 5.2 on 2025-04-29 13:51

import django.db.models.deletion
import hewan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_individu_perawat_hewan_perusahaan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jenis_hewan',
            fields=[
                ('id', models.UUIDField(default=hewan.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('nama_jenis', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'jenis_hewan',
            },
        ),
        migrations.CreateModel(
            name='Hewan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField()),
                ('url_foto', models.CharField(blank=True, max_length=100, null=True)),
                ('no_identitas_klien', models.ForeignKey(db_column='no_identitas_klien', on_delete=django.db.models.deletion.CASCADE, to='main.klien')),
                ('id_jenis', models.ForeignKey(db_column='id_jenis', on_delete=django.db.models.deletion.CASCADE, to='hewan.jenis_hewan')),
            ],
            options={
                'db_table': 'hewan',
                'constraints': [models.UniqueConstraint(fields=('nama', 'no_identitas_klien'), name='hewan_pk')],
                'unique_together': {('nama', 'no_identitas_klien')},
            },
        ),
    ]
