# Generated by Django 5.1.1 on 2025-04-29 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kunjungan_Keperawatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kunjungan', models.CharField(max_length=15)),
                ('nama_hewan', models.CharField(max_length=50)),
                ('no_identitas_klien', models.UUIDField()),
                ('no_front_desk', models.UUIDField()),
                ('no_perawat_hewan', models.UUIDField()),
                ('no_dokter_hewan', models.UUIDField()),
                ('kode_perawatan', models.CharField(max_length=10)),
                ('catatan', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kunjungan_keperawatan',
                'unique_together': {('id_kunjungan', 'nama_hewan', 'no_identitas_klien', 'no_front_desk', 'no_perawat_hewan', 'no_dokter_hewan', 'kode_perawatan')},
            },
        ),
        migrations.CreateModel(
            name='Kunjungan',
            fields=[
                ('id_kunjungan', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nama_hewan', models.CharField(max_length=50)),
                ('no_front_desk', models.UUIDField()),
                ('no_perawat_hewan', models.UUIDField()),
                ('kode_vaksin', models.CharField(blank=True, max_length=6, null=True)),
                ('tipe_kunjungan', models.CharField(max_length=10)),
                ('timestamp_awal', models.DateTimeField()),
                ('timestamp_akhir', models.DateTimeField(blank=True, null=True)),
                ('suhu', models.IntegerField()),
                ('berat_badan', models.DecimalField(decimal_places=2, max_digits=5)),
                ('no_dokter_hewan', models.ForeignKey(db_column='no_dokter_hewan', on_delete=django.db.models.deletion.CASCADE, related_name='kunjungan_dokter', to='main.dokter_hewan')),
                ('no_identitas_klien', models.ForeignKey(db_column='no_identitas_klien', on_delete=django.db.models.deletion.CASCADE, related_name='kunjungan_klien', to='main.klien')),
            ],
            options={
                'db_table': 'perawatan_hewan_kunjungan',
                'unique_together': {('id_kunjungan', 'nama_hewan', 'no_identitas_klien', 'no_front_desk', 'no_perawat_hewan', 'no_dokter_hewan')},
            },
        ),
    ]
