# Generated by Django 5.2 on 2025-04-29 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perawatan_hewan', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kunjungan',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='kunjungan',
            name='no_dokter_hewan',
        ),
        migrations.RemoveField(
            model_name='kunjungan',
            name='no_identitas_klien',
        ),
        migrations.DeleteModel(
            name='Kunjungan_Keperawatan',
        ),
        migrations.DeleteModel(
            name='Kunjungan',
        ),
    ]
