# Generated by Django 5.2 on 2025-04-28 01:31

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokter_hewan',
            fields=[
                ('no_dokter_hewan', models.UUIDField(default=main.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dokter_hewan',
            },
        ),
        migrations.CreateModel(
            name='Front_desk',
            fields=[
                ('no_front_desk', models.UUIDField(default=main.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'front_desk',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('nomor_telepon', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Klien',
            fields=[
                ('no_identitas', models.UUIDField(default=main.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('tanggal_registrasi', models.DateField()),
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'db_table': 'klien',
            },
        ),
    ]
