# Generated by Django 5.2 on 2025-04-29 13:51

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('no_identitas_klien', models.OneToOneField(db_column='no_identitas_klien', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.klien')),
                ('nama_depan', models.CharField(max_length=50)),
                ('nama_tengah', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_belakang', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'individu',
            },
        ),
        migrations.CreateModel(
            name='Perawat_hewan',
            fields=[
                ('no_perawat_hewan', models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'perawat_hewan',
            },
        ),
        migrations.CreateModel(
            name='Perusahaan',
            fields=[
                ('no_identitas_klien', models.OneToOneField(db_column='no_identitas_klien', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.klien')),
                ('nama_perusahaan', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'perusahaan',
            },
        ),
        migrations.AlterField(
            model_name='dokter_hewan',
            name='no_dokter_hewan',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='no_front_desk',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('no_pegawai', models.UUIDField(default=main.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('tanggal_mulai_kerja', models.DateField()),
                ('tanggal_akhir_kerja', models.DateField(blank=True, null=True)),
                ('email_user', models.ForeignKey(db_column='email_user', on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'db_table': 'pegawai',
            },
        ),
        migrations.CreateModel(
            name='Tenaga_medis',
            fields=[
                ('no_tenaga_medis', models.UUIDField(default=main.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('no_izin_praktik', models.CharField(max_length=20, unique=True)),
                ('no_pegawai', models.ForeignKey(db_column='no_pegawai', on_delete=django.db.models.deletion.CASCADE, to='main.pegawai')),
            ],
            options={
                'db_table': 'tenaga_medis',
            },
        ),
        migrations.CreateModel(
            name='Sertifikat_kompetensi',
            fields=[
                ('no_sertifikat_kompetensi', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_sertifikat', models.CharField(max_length=100)),
                ('no_tenaga_medis', models.ForeignKey(db_column='no_tenaga_medis', on_delete=django.db.models.deletion.CASCADE, to='main.tenaga_medis')),
            ],
            options={
                'db_table': 'sertifikat_kompetensi',
            },
        ),
        migrations.CreateModel(
            name='Jadwal_praktik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(max_length=6)),
                ('jam', models.CharField(max_length=11)),
                ('no_dokter_hewan', models.ForeignKey(db_column='no_dokter_hewan', on_delete=django.db.models.deletion.CASCADE, to='main.dokter_hewan')),
            ],
            options={
                'db_table': 'jadwal_praktik',
                'constraints': [models.UniqueConstraint(fields=('no_dokter_hewan', 'hari', 'jam'), name='jadwal_praktik_pk')],
            },
        ),
    ]
