# Generated by Django 5.1.1 on 2025-04-29 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perawatan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perawatan_Obat',
            fields=[
                ('kode_perawatan', models.ForeignKey(db_column='kode_perawatan', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='perawatan.perawatan')),
                ('kuantitas_obat', models.IntegerField()),
            ],
            options={
                'db_table': 'perawatan_obat',
                'managed': False,
            },
        ),
    ]
