# Generated by Django 5.1.1 on 2025-04-29 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('vaksin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kunjungan',
            fields=[
                ('id_kunjungan', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nama_hewan', models.CharField(max_length=50)),
                ('no_perawat_hewan', models.UUIDField()),
                ('tipe_kunjungan', models.CharField(choices=[('janji_temu', 'Janji Temu'), ('walk_in', 'Walk-In'), ('darurat', 'Darurat')], max_length=10)),
                ('timestamp_awal', models.DateTimeField()),
                ('timestamp_akhir', models.DateTimeField(blank=True, null=True)),
                ('suhu', models.IntegerField(blank=True, null=True)),
                ('berat_badan', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('kode_vaksin', models.ForeignKey(blank=True, db_column='kode_vaksin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kunjungan_app_set', to='vaksin.vaksin')),
                ('no_dokter_hewan', models.ForeignKey(db_column='no_dokter_hewan', on_delete=django.db.models.deletion.CASCADE, related_name='kunjungan_app_set', to='main.dokter_hewan')),
                ('no_front_desk', models.ForeignKey(db_column='no_front_desk', on_delete=django.db.models.deletion.CASCADE, related_name='kunjungan_app_set', to='main.front_desk')),
                ('no_identitas_klien', models.ForeignKey(db_column='no_identitas_klien', on_delete=django.db.models.deletion.CASCADE, related_name='kunjungan_app_set', to='main.klien')),
            ],
            options={
                'db_table': 'kunjungan_app',
            },
        ),
    ]
