# Generated by Django 5.1.1 on 2025-04-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perawatan',
            fields=[
                ('kode_perawatan', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('nama_perawatan', models.CharField(max_length=100)),
                ('biaya_perawatan', models.IntegerField()),
            ],
            options={
                'db_table': 'perawatan',
                'managed': False,
            },
        ),
    ]
